### ISSUE TITLE
Version 5 ROADMAP

### ISSUE THREAD

**Issue by HaNdTriX** [HaNdTriX/generator-chrome-extension-kickstart#27]
This is just a collection of thinks I would like to see in Version 5

* [ ] Switch from Gulp to [Taskr](https://www.npmjs.com/package/taskr)
* [ ] Remove Image Optimisation 
* [ ] Add chromereload to watch task via manifest change
* [ ] Improve build speed
* [ ] Improve documentation
* [ ] Reduce amount of tasks
* [ ] Add better logo
* [ ] Rename to `generator-webextension` or similar
* [ ] Improve tests
* [ ] Add jest test task
* [ ] Split into multiple yeoman generators
* [ ] Add Polyfill/Ponyfill spec and examples

Currently I don't have the time to tackle these Issues. So if someone from the community wan't to take over, feel free to drop me a note!

**Comment by yxliang01** [comment]
Hey, seems like it will be a big update. May I know the rationale behind all these changes?

**Comment by HaNdTriX** [comment]
https://github.com/HaNdTriX/generator-web-extension
https://github.com/HaNdTriX/webextension-toolbox
